# DEVELOPMENT ONLY, DO NOT USE FOR PRODUCTION
version: '3.5'

services:
  db:
    container_name: "stori-db"
    image: mysql:latest
    environment:
      MYSQL_URL: localhost
      MYSQL_PORT: 3306
      MYSQL_USER: root
      MYSQL_PASSWORD: stori_challenge
      MYSQL_NAME: stori_db
    ports:
      - "3306:3306"
